name: driver
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  sign_in_with_apple: ^6.1.2
  google_sign_in: ^6.2.1

  firebase_auth: ^4.17.4
  firebase_core: ^2.25.4
  firebase_messaging: ^14.7.10
  flutterflow_paginate_firestore: ^1.0.3+1
  firebase_storage: ^11.6.5
  firebase_database: ^10.4.0

  # firebase_storage: ^12.3.1
  firebase_app_check:

  shared_preferences: ^2.3.2
  flutter_local_notifications:

  flutter_polyline_points: ^2.1.0
  google_maps_flutter: ^2.9.0
  googleapis_auth: ^1.6.0
  geocoding: ^3.0.0
  location: ^7.0.0
  geolocator: ^13.0.1
  geoflutterfire2: ^2.3.15
  socket_io_client: ^2.0.0

  get: 4.6.6
  provider: ^6.1.2
  uuid: ^4.5.0

  country_code_picker: ^3.0.0
  flutter_easyloading: ^3.0.5
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  lottie: ^3.1.2

  otp_text_field: ^1.1.3
  flutter_overlay_loader: ^2.0.0

  crypto: ^3.0.5
  intl: ^0.19.0

  timelines_plus: ^1.0.3
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  flutter_image_compress: ^2.3.0
  url_launcher: ^6.3.0
  package_info_plus: ^8.0.2

  pie_chart: ^5.4.0
  auto_size_text_field: ^2.2.4
  flutter_widget_from_html: ^0.15.2

  #payment_dependencies
  flutter_stripe: ^11.1.0
  # flutter_paypal_native: ^2.1.0
  razorpay_flutter: ^1.3.7
  # flutterwave_standard: ^1.0.8
  mercadopago_sdk: ^1.3.0
  dotted_border: ^2.1.0
  change_app_package_name: ^1.4.0
  flutter_launcher_icons: ^0.14.1

dependency_overrides:
  http: ^1.2.2
  web: ^1.0.0
  # cloud_firestore: ^5.4.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true  

  assets:
    - assets/images/
    - assets/icon/
    - assets/animation/
